### ISSUE TITLE
rss feed on blog

### ISSUE THREAD

**Issue by hendersonmpa** [mmaul/clml.tutorials#1]
Hello Mike,

Thanks for posting the tutorials for clml. They have been very useful.  Currently the RSS feed redirects to another website.

Matthew

**Comment by mmaul** [comment]
What site is it redirecting to?

**Comment by hendersonmpa** [comment]
I am getting variations on:

http://yourdomain.com/clml.tutorials//2015/09/08/CLML-Wine-pca-k-means-and-hierarchical-clustering.html

With http://yourdomain.com as the constant domain.

**Comment by mmaul** [comment]
Okay sorted it out, Base url in config.yml wasn't set. Thanks for letting me know.

**Comment by hendersonmpa** [comment]
Just resubscribed and now there is a 404 file not found for the feed links i.e.

https://mmaul.github.io/clml.tutorials//clml.tutorials//2015/08/29/CLML-Datasets.html

When compared to the actual URL it looks like the clml.tutorials part of the URL is repeated in the RSS.

https://mmaul.github.io/clml.tutorials//2015/08/29/CLML-Datasets.html

**Comment by mmaul** [comment]
Fixed

On Sun, Nov 8, 2015 at 12:46 PM, Matthew Henderson <notifications@github.com
